# Generated by Django 4.0.3 on 2022-07-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebill',
            name='gstin',
        ),
    ]
